import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Medical Disclaimer — RxReader",
  description: "RxReader provides AI-generated prescription explanations for informational purposes only. Read our full medical disclaimer.",
};

export default function DisclaimerPage() {
  return (
    <div className="max-w-3xl mx-auto px-4 py-12">
      <h1 className="text-4xl font-extrabold text-gray-900 mb-8">Medical Disclaimer — RxReader</h1>

      <div className="space-y-8 leading-relaxed text-gray-700">
        <div className="bg-red-50 border-l-4 border-red-500 p-6 mb-8">
          <p className="text-red-800 font-bold text-lg">
            IMPORTANT: RxReader is NOT a medical device. Always consult a licensed doctor or pharmacist for medical advice.
          </p>
        </div>

        <section className="space-y-4">
          <p className="font-bold">
            Please read this disclaimer carefully before using RxReader.
          </p>
          <p>
            The information provided by RxReader is for <strong>informational purposes only</strong> and is not intended as a substitute for professional medical advice, diagnosis, or treatment.
          </p>
          <p>
            The output generated by this tool is <strong>AI-generated and may contain errors</strong>. Prescription reading is complex, and handwriting or abbreviations can be misinterpreted by AI models.
          </p>
        </section>

        <section className="space-y-4">
          <h2 className="text-2xl font-bold text-gray-900">No Professional Relationship</h2>
          <p>
            Your use of RxReader does not create a doctor-patient relationship. We are a technology service, not a medical provider.
          </p>
        </section>

        <section className="space-y-4">
          <h2 className="text-2xl font-bold text-gray-900">Critical Warnings</h2>
          <ul className="list-disc pl-5 space-y-2">
            <li><strong>Never make medical decisions</strong> based solely on the output of RxReader.</li>
            <li><strong>Always verify</strong> any results with a licensed doctor or pharmacist.</li>
            <li><strong>Do not delay</strong> seeking professional medical advice because of something you have read on this website.</li>
            <li>In case of a medical emergency, call your local emergency services or go to the nearest emergency room immediately.</li>
          </ul>
        </section>

        <section className="space-y-4">
          <h2 className="text-2xl font-bold text-gray-900">Limitation of Liability</h2>
          <p>
            RxReader and its creators are <strong>not liable for any harm, loss, or injury</strong> resulting from the use or misuse of this tool. By using RxReader, you acknowledge that you use the tool at your own risk and that you are responsible for verifying any information with a qualified medical professional.
          </p>
        </section>
      </div>
    </div>
  );
}
